In [5]:
import torch

### 요소별 산출 연산

In [6]:
import torch

In [11]:
t1 = torch.FloatTensor([[1, 2], [3, 4]])
t2 = torch.FloatTensor([[2, 2], [3, 4]])

In [17]:
print(t1 + t2, '덧셈')
print(t1 - t2, '뺄셈')
print(t1 * t2, '곱셈')
print(t1 / t2, '나눗셈')

tensor([[3., 4.],
        [6., 8.]]) 덧셈
tensor([[-1.,  0.],
        [ 0.,  0.]]) 뺄셈
tensor([[ 2.,  4.],
        [ 9., 16.]]) 곱셈
tensor([[0.5000, 1.0000],
        [1.0000, 1.0000]]) 나눗셈


In [26]:
print(t1 ** t2, '제곱')
print(t1 == t2, '같은')
print(t1 != t2, '같지 않은')

tensor([[  1.,   4.],
        [ 27., 256.]]) 제곱
tensor([[False,  True],
        [ True,  True]]) 같은
tensor([[ True, False],
        [False, False]]) 같지 않은


In [28]:
t1.mul()

tensor([[1., 2.],
        [3., 4.]])

In [29]:
t2

tensor([[2., 2.],
        [3., 4.]])

In [31]:
## inplace 연산 X
# inplace 연산을 하려면 mul_

t1.mul(t2)

tensor([[ 2.,  4.],
        [ 9., 16.]])

In [36]:
t3 = torch.FloatTensor([[3, 3], [2, 1]])
print('기존',t3)

t3.mul_(t2)
print('multiply',t3)

기존 tensor([[3., 3.],
        [2., 1.]])
multiply tensor([[6., 6.],
        [6., 4.]])


In [42]:
t3 + torch.FloatTensor([1, 2])

tensor([[7., 8.],
        [7., 6.]])

In [43]:
t3 + torch.FloatTensor([[1], [2]])

tensor([[7., 7.],
        [8., 6.]])

### 텐서 형태 변환

    - 텐서의 전체요소(element)개수는 유지한 채 모양을 바꾸는 방법

In [44]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                        [[5, 6], 
                        [7, 8]],
                        [[9, 10],
                        [10, 11]]])


print(x)
print(x.size())

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [10., 11.]]])
torch.Size([3, 2, 2])


In [46]:
print(x.view(12))
print(x.view(12).size())

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 10., 11.])
torch.Size([12])


In [47]:
print(x.view(4, 3))
print(x.view(4, 3).size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 10., 11.]])
torch.Size([4, 3])


In [48]:
## -1은 모든 요소 곱하고 남은 나머지 다 떄려박아

print(x.view(-1, 6))
print(x.view(-1, 6).size())


tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 10., 11.]])
torch.Size([2, 6])


In [49]:
x.reshape(-1, 6)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 10., 11.]])

In [51]:
x = torch.FloatTensor([
                        [[1, 2], 
                        [3, 4]]
                        ])
x.size()

torch.Size([1, 2, 2])

In [54]:
## squeeze() 함수는 차원의 수가 1인 것을 없애줘
# 인덱스 지정 가능하나 만약 지정한 인덱스가 1인 아닌 경우 원래 Tensor 반환

x.squeeze()
print(x.squeeze().size())


torch.Size([2, 2])


In [56]:
## unsqueeze() 함수는 1인 차원을 삽입
x = x.squeeze()
print(x)
print(x.size())

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


In [60]:
print(x.unsqueeze(0))
print(x.unsqueeze(0).size())


tensor([[[1., 2.],
         [3., 4.]]])
torch.Size([1, 2, 2])


### 텐서 자르기 & 붙이기

In [67]:
x = torch.FloatTensor([[[1, 2], 
                       [3, 4]],
                        [[5, 6],
                        [7, 8]],
                        [[9, 10],
                        [11, 12]]])
print(x.size())

torch.Size([3, 2, 2])


In [68]:
x[0]

tensor([[1., 2.],
        [3., 4.]])

In [69]:
x[-1]

tensor([[ 9., 10.],
        [11., 12.]])

In [70]:
x[:, 0]

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])

In [75]:
x[:, 1]

tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]])

In [77]:
x[1:2, 1:, :]

tensor([[[7., 8.]]])

In [80]:
x = torch.FloatTensor(10, 4)
print(x)
print(x.size())

tensor([[ 0.0000e+00,  8.5899e+09, -3.5679e-23,  2.0005e+00],
        [ 2.1019e-44,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  5.2478e-08,  1.0665e-08],
        [ 0.0000e+00,  8.5899e+09,  0.0000e+00,  8.5899e+09],
        [ 1.3577e+22,  2.6258e-06,  3.3829e+21,  2.1707e-18]])
torch.Size([10, 4])


In [82]:
splits = x.split(4, dim = 0) # 첫 번쨰 차원이 4가 되도록 전체 텐서를 나눈다

for i,s in enumerate(splits):
    print(f'{i}번째 부분텐서\n{s}\n사이즈{s.size()}')

0번째 부분텐서
tensor([[ 0.0000e+00,  8.5899e+09, -3.5679e-23,  2.0005e+00],
        [ 2.1019e-44,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])
사이즈torch.Size([4, 4])
1번째 부분텐서
tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 5.2478e-08, 1.0665e-08]])
사이즈torch.Size([4, 4])
2번째 부분텐서
tensor([[0.0000e+00, 8.5899e+09, 0.0000e+00, 8.5899e+09],
        [1.3577e+22, 2.6258e-06, 3.3829e+21, 2.1707e-18]])
사이즈torch.Size([2, 4])


In [83]:
x = torch.FloatTensor(8, 4)

chunks = x.chunk(3, dim=0) # 원하는 몇개의 부분으로 나누는 것! (3개로 나눠줘)

for i, c in enumerate(chunks):
    print(f'{i}번째 부분텐서\n{c}\n사이즈{c.size()}')


0번째 부분텐서
tensor([[0.0000e+00, 8.5899e+09, 0.0000e+00, 8.5899e+09],
        [1.9618e-44, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.3346e-09, 7.7052e+31, 7.2148e+22]])
사이즈torch.Size([3, 4])
1번째 부분텐서
tensor([[1.5766e-19, 1.0256e-08, 1.6802e-04, 3.0956e+12],
        [4.3354e-08, 1.6997e-04, 6.8626e-07, 1.2963e+16],
        [2.1707e-18, 7.0952e+22, 1.7748e+28, 1.8176e+31]])
사이즈torch.Size([3, 4])
2번째 부분텐서
tensor([[7.2708e+31, 5.0778e+31, 3.2608e-12, 1.7728e+28],
        [7.0367e+22, 2.1715e-18, 5.2478e-08, 1.0665e-08]])
사이즈torch.Size([2, 4])


In [96]:
x = torch.FloatTensor([[[1, 1],
                        [3, 4]],
                        [[5, 6],
                        [7, 8]],
                        [[9, 10],
                        [11, 12]]])
        

indices = torch.LongTensor([2, 1])

x.index_select(dim=0, index=indices)


tensor([[[ 9., 10.],
         [11., 12.]],

        [[ 5.,  6.],
         [ 7.,  8.]]])

In [102]:
t1 = torch.FloatTensor([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])
t2 = torch.FloatTensor([[10, 11, 12],
                        [13, 14, 15],
                        [16, 17, 18]])

print(t1.size(), t2.size())

print(torch.cat(tensors=[t1, t2], dim=0))
print(torch.cat(tensors=[t1, t2], dim = 0).size())

print(torch.cat(tensors=[t1, t2], dim = 1))
print(torch.cat(tensors=[t1, t2], dim = 1).size())

# torch.cat(t1, t2)

torch.Size([3, 3]) torch.Size([3, 3])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])
tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


In [111]:
print(torch.stack([t1, t2]))
print(torch.stack([t1, t2]).size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


### 유용한 함수들


## expand 함수
    - 차원의 크기가 1인 차원을 원하는 크기로 늘려주는 역할 수행

In [116]:
x = torch.FloatTensor([[[1, 2]],
                        [[3, 4]]])

print(x)
print(x.size())

tensor([[[1., 2.]],

        [[3., 4.]]])
torch.Size([2, 1, 2])


In [117]:
y = x.expand(2, 3, 2)
print(y)
print(y.size())

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])
torch.Size([2, 3, 2])


In [122]:
## Random Permuation
# 랜덤수열 생성

x = torch.randperm(10)
x.size()

torch.Size([10])

In [125]:
## argmax
# 출력값을 최대로 만드는 입력값 반환

x = torch.randperm(3 ** 3).reshape(3, 3, -1)
print(x)
print(x.size())

tensor([[[ 8, 18, 21],
         [22,  2, 24],
         [26,  3, 13]],

        [[17, 25, 16],
         [12, 23,  6],
         [ 1, 11, 14]],

        [[19,  0,  9],
         [ 5,  7, 10],
         [ 4, 20, 15]]])
torch.Size([3, 3, 3])


In [128]:
y = x.argmax(dim = -1)
y

tensor([[2, 2, 0],
        [1, 1, 2],
        [0, 2, 1]])

In [130]:
y = x.argmax(dim = 0)
y

tensor([[2, 1, 0],
        [0, 1, 0],
        [0, 2, 2]])

In [136]:
y = x.argmax(dim = 1)
y

tensor([[2, 0, 1],
        [0, 0, 0],
        [0, 2, 2]])

In [137]:
## topk 함수
# argmax는 가장 큰 1개, topk 함수는 k개까지 value, index 튜플로 반환

values, indices = torch.topk(x, k=2, dim = -1)
print(values)
print(values.size())

tensor([[[21, 18],
         [24, 22],
         [26, 13]],

        [[25, 17],
         [23, 12],
         [14, 11]],

        [[19,  9],
         [10,  7],
         [20, 15]]])
torch.Size([3, 3, 2])


In [141]:
values, indices = torch.topk(x, k=x.size(-1), largest=True)
print(x)
print(values)

tensor([[[ 8, 18, 21],
         [22,  2, 24],
         [26,  3, 13]],

        [[17, 25, 16],
         [12, 23,  6],
         [ 1, 11, 14]],

        [[19,  0,  9],
         [ 5,  7, 10],
         [ 4, 20, 15]]])
tensor([[[21, 18,  8],
         [24, 22,  2],
         [26, 13,  3]],

        [[25, 17, 16],
         [23, 12,  6],
         [14, 11,  1]],

        [[19,  9,  0],
         [10,  7,  5],
         [20, 15,  4]]])


In [146]:
## masked fill 함수
# 원하는 부분만 바꿀 때 사용

x = torch.FloatTensor([i for i in range(9)]).reshape(3, -1)

mask = x > 4
print(mask)

x.masked_fill(mask, value=-1)


tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])


tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])

In [147]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [148]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [154]:
x = torch.Tensor(range(15)).reshape(5, 3)
print(x)

print(torch.zeros_like(x))
print(torch.ones_like(x))

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.],
        [12., 13., 14.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
