### Gradient Descent 구현

In [2]:
import torch
import torch.nn.functional as F


In [20]:
## Target Tensor

target = torch.FloatTensor([[.1, .2, .3],
                            [.4, .5, .6],
                            [.7, .8, .9]])

In [21]:
x = torch.rand_like(target)
x.requires_grad = True ## gradient 업데이트 허용 !! (필수)
print(x)

tensor([[0.2360, 0.3948, 0.9065],
        [0.3604, 0.5385, 0.3750],
        [0.8618, 0.0517, 0.8717]], requires_grad=True)


In [22]:
## Loss 구하기

loss = F.mse_loss(x, target)
print(loss)

tensor(0.1183, grad_fn=<MseLossBackward>)


In [23]:
threshold = 1e-5 # 0.00001
lr = 1.       # 0.1 (Learning Rate)
iter_cnt = 0     # 반복 횟수


while loss >= threshold:
    iter_cnt += 1

    loss.backward()  # gradients Calculration.
                     # x.grad에 자동적으로 저장됨..!  (이떄 loss값은 Scalar값이어야함)

    x = x - lr * x.grad

    x.detach_()
    x.requires_grad_(True)

    loss = F.mse_loss(x, target)

    print(f'{iter_cnt}-th Loss : {loss}')
    print(x)



1-th Loss : 0.07158425450325012
tensor([[0.2058, 0.3515, 0.7718],
        [0.3692, 0.5299, 0.4250],
        [0.8258, 0.2180, 0.8780]], requires_grad=True)
2-th Loss : 0.04330405220389366
tensor([[0.1823, 0.3178, 0.6669],
        [0.3761, 0.5233, 0.4639],
        [0.7979, 0.3473, 0.8829]], requires_grad=True)
3-th Loss : 0.026196278631687164
tensor([[0.1640, 0.2916, 0.5854],
        [0.3814, 0.5181, 0.4941],
        [0.7761, 0.4479, 0.8867]], requires_grad=True)
4-th Loss : 0.015847129747271538
tensor([[0.1498, 0.2713, 0.5220],
        [0.3855, 0.5141, 0.5177],
        [0.7592, 0.5261, 0.8896]], requires_grad=True)
5-th Loss : 0.009586538188159466
tensor([[0.1387, 0.2554, 0.4726],
        [0.3887, 0.5110, 0.5360],
        [0.7460, 0.5870, 0.8919]], requires_grad=True)
6-th Loss : 0.005799262318760157
tensor([[0.1301, 0.2431, 0.4343],
        [0.3912, 0.5085, 0.5502],
        [0.7358, 0.6343, 0.8937]], requires_grad=True)
7-th Loss : 0.0035081948153674603
tensor([[0.1234, 0.2335, 0.4044]

### Pytorch autograd

In [24]:
x = torch.FloatTensor([[1, 2],
                        [3, 4]]).requires_grad_(True)

## requires_grad 속성이 True인 텐서가 있을 떄 이 텐서가 들어간 연산의 결과인 텐서도 requires_grad 속성이 True로 저장됨

In [26]:
x1 = x + 2
print(f'---- x1 ----\n{x1}')

x2 = x - 2
print(f'---- x2 ----\n{x2}')

x3 = x1 * x2
print(f'---- x3 ----\n{x3}')

x4 = x3.sum()
print(f'---- x4 ----\n{x4}')

---- x1 ----
tensor([[3., 4.],
        [5., 6.]], grad_fn=<AddBackward0>)
---- x2 ----
tensor([[-1.,  0.],
        [ 1.,  2.]], grad_fn=<SubBackward0>)
---- x3 ----
tensor([[-3.,  0.],
        [ 5., 12.]], grad_fn=<MulBackward0>)
---- x4 ----
14.0


In [27]:
x4.backward()

In [28]:
x.grad

tensor([[2., 4.],
        [6., 8.]])

In [29]:
x3.detach_()  # 메모리 해제 (그래프로부터 뗴어낼 수 있음)

tensor([[-3.,  0.],
        [ 5., 12.]])

In [34]:
x4

tensor(14., grad_fn=<SumBackward0>)